### ISSUE TITLE
angle_metal_backend: out of date drawElements/drawIndexed

### ISSUE THREAD

**Issue by kakashidinho** [elix22/Urho3D#20]
Hi Eli,
Thanks for trying out ANGLE's Metal backend on Urtho3D. I noticed you are using out of date version of MetalANGLE. The latest version might already contain fix for the drawElements() issue without your hack/fix. 
Maybe you could give it a try?
Thanks, this Urtho3D project is a great way to test Metal backend. I will test it myself also.

**Comment by elix22** [comment]
Hi Le Hoang Quyen ,
I will try it during this weekend and will let you know 
Thanks

**Comment by elix22** [comment]
I upmerged to your latest code .
Issues still exist ...
All my hacks are under the URHO3D_ANGLE_METAL  CC

**Comment by kakashidinho** [comment]
May I know which samples causing the issues? So that I can test them myself.
Thanks,

**Comment by elix22** [comment]
07_Billboards  - drawElements/drawIndexed  issue
50_Urho2DPlatformer - mimaps issue   .

**Comment by elix22** [comment]
up merged to  latest upstream

**Comment by kakashidinho** [comment]
Thanks for trying out and notifying me. Looks like I have found out the bug in index buffer conversion.

**Comment by elix22** [comment]
Happy to help 
Let me know once you fixed it , I will merge your latest and will try it

**Comment by kakashidinho** [comment]
I have fixed the 2 issues. For the mipmaps issue, it is actually the spec of GLES 2.0 saying that non-power-of-two textures won't support mipmaps unless OES_texture_npot extension is supported. I haven't supported that extension yet.
Anw, The urho3d project is strange, when i modify the metal backend's source code, then clicking run, the project doesn't relink the newly compiled metal backend code. As a result, the sample code will still run with the out of date code. I have to force delete everything, and rebuild from scratch, then it will link against the up to date code.
